use anyhow::{anyhow, Context, Result};
use chrono::Local;
use std::fs;
use std::path::{Path, PathBuf};

use crate::project_context::ProjectContext;

const INDEX_FILE_NAME: &str = "index.md";
const GENERATED_MARKER: &str = "<!-- vybrid-generated-index -->";
const DEFAULT_MAX_CHARS: usize = 12_000;
const MAX_FILES: usize = 300;

#[derive(Debug, Clone)]
struct IndexEntry {
    path: String,
    kind: &'static str,
}

pub fn index_path() -> PathBuf {
    ProjectContext::discover().root().join(INDEX_FILE_NAME)
}

pub fn read_project_index() -> Result<String> {
    let ctx = ProjectContext::discover();
    let path = ctx.root().join(INDEX_FILE_NAME);
    if !path.exists() {
        return Ok(format!(
            "No `{}` found at project root `{}`. Use `generate_project_index` or `/index refresh` before broad project navigation.",
            INDEX_FILE_NAME,
            ctx.root().display()
        ));
    }
    let content =
        fs::read_to_string(&path).with_context(|| format!("Failed to read {}", path.display()))?;
    Ok(format!(
        "Project index `{}`:\n\n{}",
        ctx.root_relative(&path),
        content
    ))
}

pub fn generate_project_index(force: bool) -> Result<String> {
    let ctx = ProjectContext::discover();
    let path = ctx.root().join(INDEX_FILE_NAME);

    if path.exists() {
        let existing = fs::read_to_string(&path)
            .with_context(|| format!("Failed to read existing {}", path.display()))?;
        if !existing.contains(GENERATED_MARKER) && !force {
            return Err(anyhow!(
                "`{}` already exists and does not look generated by Vybrid. Refusing to overwrite it.",
                path.display()
            ));
        }
    }

    let content = build_index(&ctx)?;
    fs::write(&path, &content).with_context(|| format!("Failed to write {}", path.display()))?;

    Ok(format!(
        "Generated `{}` ({} bytes). Paths in the index are root-relative.",
        ctx.root_relative(&path),
        content.len()
    ))
}

fn build_index(ctx: &ProjectContext) -> Result<String> {
    let mut entries = Vec::new();
    collect_entries(ctx.root(), ctx.root(), &mut entries)?;
    entries.sort_by(|a, b| a.path.cmp(&b.path));
    entries.truncate(MAX_FILES);

    let manifests = entries
        .iter()
        .filter(|entry| {
            matches!(
                entry.path.as_str(),
                "Cargo.toml" | "package.json" | "pyproject.toml" | "go.mod" | "deno.json"
            ) || entry.path.ends_with("/Cargo.toml")
                || entry.path.ends_with("/package.json")
        })
        .map(|entry| format!("- `{}`", entry.path))
        .collect::<Vec<_>>();

    let entrypoints = entries
        .iter()
        .filter(|entry| {
            matches!(
                entry.path.as_str(),
                "src/main.rs" | "src/lib.rs" | "main.rs" | "app/main.rs" | "src/index.ts"
            ) || entry.path.ends_with("/src/main.rs")
                || entry.path.ends_with("/src/lib.rs")
        })
        .take(30)
        .map(|entry| format!("- `{}`", entry.path))
        .collect::<Vec<_>>();

    let source_files = entries
        .iter()
        .filter(|entry| entry.kind == "source")
        .take(120)
        .map(|entry| format!("- `{}`", entry.path))
        .collect::<Vec<_>>();

    let mut out = String::new();
    out.push_str(GENERATED_MARKER);
    out.push('\n');
    out.push_str("# Project Index\n\n");
    out.push_str("Generated by Vybrid. Keep paths root-relative when using tools.\n\n");
    out.push_str(&format!("- Project root: `{}`\n", ctx.root().display()));
    out.push_str(&format!(
        "- Generated: `{}`\n",
        Local::now().format("%Y-%m-%d %H:%M:%S")
    ));
    out.push_str(&format!("- Indexed files shown: `{}`\n\n", entries.len()));

    out.push_str("## Manifests\n");
    if manifests.is_empty() {
        out.push_str("- None detected in indexed files.\n\n");
    } else {
        out.push_str(&manifests.join("\n"));
        out.push_str("\n\n");
    }

    out.push_str("## Entrypoints\n");
    if entrypoints.is_empty() {
        out.push_str("- None detected in indexed files.\n\n");
    } else {
        out.push_str(&entrypoints.join("\n"));
        out.push_str("\n\n");
    }

    out.push_str("## Top-Level Directories\n");
    for dir in top_level_dirs(&entries) {
        out.push_str(&format!("- `{dir}/`\n"));
    }
    out.push('\n');

    out.push_str("## Source And Config Map\n");
    out.push_str(&source_files.join("\n"));
    out.push_str("\n\n");

    out.push_str("## Navigation Notes\n");
    out.push_str("- Read this index before broad `ls`, glob, or full-file reads.\n");
    out.push_str("- Use root-relative paths exactly as listed here.\n");
    out.push_str("- If more detail is needed, read only the specific file or line range.\n");

    Ok(truncate_chars(&out, DEFAULT_MAX_CHARS))
}

fn collect_entries(root: &Path, dir: &Path, entries: &mut Vec<IndexEntry>) -> Result<()> {
    if entries.len() >= MAX_FILES {
        return Ok(());
    }

    let mut children = fs::read_dir(dir)
        .with_context(|| format!("Failed to read directory {}", dir.display()))?
        .collect::<std::result::Result<Vec<_>, _>>()
        .with_context(|| format!("Failed to list directory {}", dir.display()))?;
    children.sort_by_key(|entry| entry.path());

    for child in children {
        if entries.len() >= MAX_FILES {
            break;
        }
        let path = child.path();
        let name = child.file_name();
        let name = name.to_string_lossy();
        if should_skip_name(&name) {
            continue;
        }

        let rel = path.strip_prefix(root).unwrap_or(&path);
        if path.is_dir() {
            collect_entries(root, &path, entries)?;
        } else if should_include_file(&path) {
            entries.push(IndexEntry {
                path: rel.display().to_string(),
                kind: file_kind(&path),
            });
        }
    }

    Ok(())
}

fn should_skip_name(name: &str) -> bool {
    matches!(
        name,
        ".git"
            | "target"
            | "node_modules"
            | "dist"
            | "build"
            | ".next"
            | ".cache"
            | ".venv"
            | "__pycache__"
    )
}

fn should_include_file(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|s| s.to_str()) else {
        return false;
    };
    if name == INDEX_FILE_NAME {
        return false;
    }
    if matches!(
        name,
        "Cargo.toml" | "Cargo.lock" | "package.json" | "pyproject.toml" | "go.mod" | "README.md"
    ) {
        return true;
    }
    matches!(
        path.extension().and_then(|s| s.to_str()),
        Some(
            "rs" | "ts"
                | "tsx"
                | "js"
                | "jsx"
                | "json"
                | "toml"
                | "yaml"
                | "yml"
                | "md"
                | "py"
                | "go"
                | "java"
                | "c"
                | "cpp"
                | "h"
        )
    )
}

fn file_kind(path: &Path) -> &'static str {
    match path.extension().and_then(|s| s.to_str()) {
        Some("rs" | "ts" | "tsx" | "js" | "jsx" | "py" | "go" | "java" | "c" | "cpp" | "h") => {
            "source"
        }
        _ => "config",
    }
}

fn top_level_dirs(entries: &[IndexEntry]) -> Vec<String> {
    let mut dirs = entries
        .iter()
        .filter_map(|entry| entry.path.split_once('/').map(|(dir, _)| dir))
        .filter(|dir| !dir.is_empty())
        .map(str::to_string)
        .collect::<Vec<_>>();
    dirs.sort();
    dirs.dedup();
    dirs
}

fn truncate_chars(input: &str, max_chars: usize) -> String {
    if input.chars().count() <= max_chars {
        return input.to_string();
    }
    let mut out = input.chars().take(max_chars).collect::<String>();
    out.push_str("\n\n[Index truncated; regenerate with a higher budget in code if needed.]\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_index_skips_build_dirs() {
        let root = std::env::temp_dir().join(format!("vybrid-index-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(root.join("src")).unwrap();
        fs::create_dir_all(root.join("target")).unwrap();
        fs::write(root.join("Cargo.toml"), "[package]\nname = \"demo\"\n").unwrap();
        fs::write(root.join("src/lib.rs"), "pub fn demo() {}\n").unwrap();
        fs::write(root.join("target/nope.rs"), "ignored\n").unwrap();

        let ctx = ProjectContext::from_root(&root);
        let index = build_index(&ctx).unwrap();
        let _ = fs::remove_dir_all(&root);

        assert!(index.contains("Cargo.toml"));
        assert!(index.contains("src/lib.rs"));
        assert!(!index.contains("target/nope.rs"));
        assert!(index.len() <= DEFAULT_MAX_CHARS + 128);
    }
}
